### ISSUE TITLE
Page Media Image Resizer feature won't work

### ISSUE THREAD

**Issue by tomceek** [getgrav/grav-plugin-admin#1426]
New added feature won't work at all - no manipulation to resolution according settings are applied.
Also, picture quality settings could be changed by 1:

![admin-bug](https://user-images.githubusercontent.com/30144585/38880487-87a6d4bc-426e-11e8-8699-d359d9e28e2e.jpg)

**Comment by underr-ua** [comment]
I have the same

**Comment by rhukster** [comment]
This has been fixed already: https://github.com/getgrav/grav-plugin-admin/commit/70208bea7ba1ea327664655752863ca8538d34af

**Comment by tomceek** [comment]
Resolution manipulation options Max Width and Max Height still won't work after update to v1.8.1

![image](https://user-images.githubusercontent.com/30144585/40114114-5c38adf2-5914-11e8-9143-3741fab4b596.png)

Only Resize Width & Resize Height options works
